---------------------------------------------------------------------------------
-- ファイターリストテーブル登録
---------------------------------------------------------------------------------
INSERT INTO sumabura.fighter_list VALUES ('1', 'マリオ', 'マリオ', E'');
INSERT INTO sumabura.fighter_list VALUES ('2', 'ドンキーコング', 'DK', E'');
INSERT INTO sumabura.fighter_list VALUES ('3', 'リンク', 'リンク', E'');
INSERT INTO sumabura.fighter_list VALUES ('4', 'サムス・ダークサムス', 'ダムス', E'');
INSERT INTO sumabura.fighter_list VALUES ('6', 'ヨッシー', 'ヨッシー', E'');
INSERT INTO sumabura.fighter_list VALUES ('7', 'カービィ', 'CB', E'');
INSERT INTO sumabura.fighter_list VALUES ('8', 'フォックス', 'FX', E'急降下回避\r\n弱、横強、DA,、降り空前、空後\r\n崖狩り空前、空上\r\n\r\n復帰阻止：NB\r\n下強＋空前\r\n空N＋上スマ（100%) 　※横スマ（85%)');
INSERT INTO sumabura.fighter_list VALUES ('9', 'ピカチュウ', 'ピカ', E'');
INSERT INTO sumabura.fighter_list VALUES ('10', 'ルイージ', 'L', E'');
INSERT INTO sumabura.fighter_list VALUES ('11', 'ネス', 'ネス', E'');
INSERT INTO sumabura.fighter_list VALUES ('12', 'キャプテン・ファルコン', 'CF', E'');
INSERT INTO sumabura.fighter_list VALUES ('13', 'プリン', 'プリン', E'');
INSERT INTO sumabura.fighter_list VALUES ('14', 'ピーチ・デイジー', 'ピチデ', E'');
INSERT INTO sumabura.fighter_list VALUES ('16', 'クッパ', 'カメ', E'');
INSERT INTO sumabura.fighter_list VALUES ('17', 'アイスクライマー', 'アイクラ', E'');
INSERT INTO sumabura.fighter_list VALUES ('18', 'シーク', 'シーク', E'');
INSERT INTO sumabura.fighter_list VALUES ('19', 'ゼルダ', 'ゼルダ', E'');
INSERT INTO sumabura.fighter_list VALUES ('20', 'ドクターマリオ', 'ドクマリ', E'');
INSERT INTO sumabura.fighter_list VALUES ('21', 'ピチュー', 'ピチュー', E'');
INSERT INTO sumabura.fighter_list VALUES ('22', 'ファルコ', 'ファルコ', E'');
INSERT INTO sumabura.fighter_list VALUES ('23', 'マルス', 'マルス', E'');
INSERT INTO sumabura.fighter_list VALUES ('24', 'ルキナ', 'ルキナ', E'');
INSERT INTO sumabura.fighter_list VALUES ('25', 'こどもリンク', 'ヤンリン', E'');
INSERT INTO sumabura.fighter_list VALUES ('26', 'ガノンドルフ', 'ガノン', E'');
INSERT INTO sumabura.fighter_list VALUES ('27', 'ミュウツー', 'M2', E'');
INSERT INTO sumabura.fighter_list VALUES ('28', 'ロイ', 'ロイ', E'');
INSERT INTO sumabura.fighter_list VALUES ('29', 'クロム', 'クロム', E'');
INSERT INTO sumabura.fighter_list VALUES ('30', 'Mr.ゲーム&ウォッチ', 'ゲッチ', E'');
INSERT INTO sumabura.fighter_list VALUES ('31', 'メタナイト', 'メタ', E'');
INSERT INTO sumabura.fighter_list VALUES ('32', 'ピット・ブラックピット', 'ブラピ', E'');
INSERT INTO sumabura.fighter_list VALUES ('34', 'ゼロスーツサムス', 'ゼロサム', E'');
INSERT INTO sumabura.fighter_list VALUES ('35', 'ワリオ', 'ワリオ', E'');
INSERT INTO sumabura.fighter_list VALUES ('36', 'スネーク', 'スネーク', E'');
INSERT INTO sumabura.fighter_list VALUES ('37', 'アイク', 'アイクラ', E'');
INSERT INTO sumabura.fighter_list VALUES ('38', 'ポケモントレーナー', 'ポケトレ', E'');
INSERT INTO sumabura.fighter_list VALUES ('39', 'ディディーコング', 'DD', E'');
INSERT INTO sumabura.fighter_list VALUES ('40', 'リュカ', 'リュカ', E'中距離時：PKF、空前、横強（基本、前に飛ばないように）\r\n密着時：下強、空N、弱\r\n\r\n撃墜：PKS、投げ、PKF（基本、復帰阻止）\r\n※スマッシュは当たらないので基本使わない。');
INSERT INTO sumabura.fighter_list VALUES ('41', 'ソニック', 'ソニック', E'');
INSERT INTO sumabura.fighter_list VALUES ('42', 'デデデ', 'DDD', E'');
INSERT INTO sumabura.fighter_list VALUES ('43', 'ピクミン＆オリマー', 'ピクオリ', E'');
INSERT INTO sumabura.fighter_list VALUES ('44', 'ルカリオ', 'ルカリオ', E'');
INSERT INTO sumabura.fighter_list VALUES ('45', 'ロボット', 'ロボット', E'中距離を保ち続ける。（地上戦が多い）\r\nコマのタイミング（焦らし）\r\n地上：前ステ下強、前ステ掴み、DA、横強\r\n空中：空N＋空前\r\n\r\n頻繁：コマ、下強、空前\r\n空N、空後は置き技\r\n横Bはあんまり降らない。\r\n');
INSERT INTO sumabura.fighter_list VALUES ('46', 'トゥーンリンク', 'トリン', E'');
INSERT INTO sumabura.fighter_list VALUES ('47', 'ウルフ', 'ウルフ', E'');
INSERT INTO sumabura.fighter_list VALUES ('48', 'むらびと', 'むらびと', E'');
INSERT INTO sumabura.fighter_list VALUES ('49', 'ロックマン', '岩', E'');
INSERT INTO sumabura.fighter_list VALUES ('50', 'Wii Fit トレーナー', 'フィットレ', E'');
INSERT INTO sumabura.fighter_list VALUES ('51', 'ロゼッタ＆チコ', 'ロゼチコ', E'');
INSERT INTO sumabura.fighter_list VALUES ('52', 'リトルマック', 'リトマ', E'');
INSERT INTO sumabura.fighter_list VALUES ('53', 'ゲッコウガ', 'ゲコ', E'');
INSERT INTO sumabura.fighter_list VALUES ('54', '格闘Mii', 'カクミ', E'');
INSERT INTO sumabura.fighter_list VALUES ('55', '剣術Mii', 'ケンミ', E'');
INSERT INTO sumabura.fighter_list VALUES ('56', '射撃Mii', 'シャゲミ', E'');
INSERT INTO sumabura.fighter_list VALUES ('57', 'パルテナ', 'パルテナ', E'');
INSERT INTO sumabura.fighter_list VALUES ('58', 'パックマン', '金玉', E'');
INSERT INTO sumabura.fighter_list VALUES ('59', 'ルフレ', 'ルフレ', E'');
INSERT INTO sumabura.fighter_list VALUES ('60', 'シュルク', '手越', E'');
INSERT INTO sumabura.fighter_list VALUES ('61', 'クッパJr.', 'パジュニ', E'');
INSERT INTO sumabura.fighter_list VALUES ('62', 'ダックハント', '犬', E'');
INSERT INTO sumabura.fighter_list VALUES ('63', 'リュウ', 'リュウ', E'小足＋中足\r\n\r\n＜遠距離＞\r\n波動拳：反対方向から下回りで打ちたい方向向ける\r\n竜巻旋風脚：逆方向に下から向ける。\r\n\r\n＜撃墜＞\r\n空後\r\n昇竜拳：最風と一緒');
INSERT INTO sumabura.fighter_list VALUES ('64', 'ケン', '剣', E'');
INSERT INTO sumabura.fighter_list VALUES ('65', 'クラウド', 'クラウド', E'');
INSERT INTO sumabura.fighter_list VALUES ('66', 'カムイ', 'カムイ', E'');
INSERT INTO sumabura.fighter_list VALUES ('67', 'ベヨネッタ', 'ベヨネッタ', E'');
INSERT INTO sumabura.fighter_list VALUES ('68', 'インクリング', 'イカ', E'');
INSERT INTO sumabura.fighter_list VALUES ('69', 'リドリー', 'リドリー', E'密着を避ける。\r\n相手の方向に体を向け続ける。（撃墜時は背中を向ける）\r\n下強or横強\r\n下投げ＋空前　or　D\r\n下投げ + 空N　＋弱（高パーセントを狙えるが難しい）\r\n\r\n＜小技＞\r\n空前崖上がりがファイターの中で強い。\r\n大ジャンプ空前急降下　＋　弱が通る。（難）\r\n横B　＋　横B　＋空N　＋ジャンプ２回で戻る。\r\n\r\n＜弱点＞\r\n軽い\r\n密着に弱い\r\nコンボ耐性ない\r\n復帰阻止に弱い');
INSERT INTO sumabura.fighter_list VALUES ('70', 'シモン・リヒター', 'シモリヒ', E'');
INSERT INTO sumabura.fighter_list VALUES ('72', 'キングクルール', 'キンクル', E'');
INSERT INTO sumabura.fighter_list VALUES ('73', 'しずえ', 'しずえ', E'');
INSERT INTO sumabura.fighter_list VALUES ('74', 'ガオガエン', 'ガエン', E'');
INSERT INTO sumabura.fighter_list VALUES ('75', 'パックンフラワー', '草', E'');
INSERT INTO sumabura.fighter_list VALUES ('76', 'ジョーカー', 'J', E'');
INSERT INTO sumabura.fighter_list VALUES ('77', '勇者', '勇者', E'');
INSERT INTO sumabura.fighter_list VALUES ('78', 'バンジョー＆カズーイ', 'バンカズ', E'');
INSERT INTO sumabura.fighter_list VALUES ('79', 'テリー', 'テリー', E'');
INSERT INTO sumabura.fighter_list VALUES ('80', 'ベレトス', 'ベレトス', E'');
INSERT INTO sumabura.fighter_list VALUES ('81', 'ミェンミェン', 'メン', E'');
INSERT INTO sumabura.fighter_list VALUES ('82', 'スティーブ', 'スティーブ', E'下投げ＋横スマ\r\nクラフトボックスの移動：ガード＋B');
INSERT INTO sumabura.fighter_list VALUES ('83', 'セフィロス', 'セフィロス', E'');
INSERT INTO sumabura.fighter_list VALUES ('84', 'ホムヒカ', 'ホムヒカ', E'');
INSERT INTO sumabura.fighter_list VALUES ('85', 'カズヤ', 'カズヤ', E'');
INSERT INTO sumabura.fighter_list VALUES ('86', 'ソラ', 'ソラ', E'');

---------------------------------------------------------------------------------
-- プレイヤー管理テーブル登録
---------------------------------------------------------------------------------
INSERT INTO sumabura.myfighters VALUES ('7', 'カービィ', 'CB', '#ffff00', '1269', '1261', '1220');
INSERT INTO sumabura.myfighters VALUES ('86', 'ソラ', 'ソラ', '#0000ff', '1021', '1019', '900');
INSERT INTO sumabura.myfighters VALUES ('26', 'ガノンドルフ', 'ガノン', '#800080', '856', '524', '859');
INSERT INTO sumabura.myfighters VALUES ('57', 'パルテナ', 'パルテナ', '#ff0000', '835', '831', '801');
INSERT INTO sumabura.myfighters VALUES ('12', 'キャプテン・ファルコン', 'CF', '#696969', '860', '839', '381');
INSERT INTO sumabura.myfighters VALUES ('27', 'ミュウツー', 'M2', '#ffffff', '843', '839', '750');
INSERT INTO sumabura.myfighters VALUES ('16', 'クッパ', 'カメ', '#ffff00', '737', '610', '345');

---------------------------------------------------------------------------------
-- 勝率管理テーブル登録
---------------------------------------------------------------------------------
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '1', 'マリオ', 'マリオ', '30', '11', E'8%は前投げ+空前が当たらない\r\nガード⇒掴み回避\r\n○：空後、空前、下強\r\n△：横強\r\n復帰は帰ることに専念。上Bを使用しない。');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '2', 'ドンキーコング', 'DK', '20', '18', E'0%：前投げ＋空前＋（反転）上強＋上スマ\r\n30%：空N＋横強＋下強＋下強＋空下+下強＋下強＋横スマ70%：空N＋上強＋空上　or 2段ジャンプ空後\r\n100%：【根本】空前（1段）＋横スマ　（困難）\r\n100%：【先端】空前（1段）＋空後');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '3', 'リンク', 'リンク', '5', '5', E'　');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '4', 'サムス・ダークサムス', 'ダムス', '8', '8', E'初手：空前＋上強＋上強\r\n中盤：コピー\r\n終盤：上スマ');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '6', 'ヨッシー', 'ヨッシー', '4', '1', E'16%までは前投げ+空前が当たらない\r\nステージ上で戦闘\r\n常に空後、空Nでけん制\r\n避け：下回避\r\n\r\n終盤：吸い込み掃き出し\r\n');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '7', 'カービィ', 'CB', '12', '18', E'3%は前投げ+空前が当たらない\r\nダッシュガード\r\n初手：掴み回避 → 空N\r\n後半：ガード');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '8', 'フォックス', 'FX', '3', '4', E'走って掴むことをしない\r\nガード\r\n下強\r\n引き降り空N');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '9', 'ピカチュウ', 'ピカ', '8', '5', E'3%は前投げ+空前が当たらない\r\n下強');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '10', 'ルイージ', 'L', '1', '6', E'低い位置の空中攻撃オンパレードでけん制\r\n空前、DA\r\n撃墜：ディレイ空後');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '11', 'ネス', 'ネス', '7', '8', E'3%までは前投げ+空前が当たらない\r\n序盤：歩きガード\r\n（ステップ禁止）\r\n降り空N、空前、下強、上強');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '12', 'キャプテン・ファルコン', 'CF', '12', '10', E'しゃがみ\r\n初手：掴み回避\r\n中盤：空中読み回避\r\n撃墜：ガード');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '13', 'プリン', 'プリン', '6', '3', E'3%までは前投げ+空前が当たらない\r\nガード');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '14', 'ピーチ・デイジー', 'ピチデ', '0', '3', E'ガード長（コピー推奨）\r\n浮遊している時は無視で');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '16', 'クッパ', 'カメ', '8', '9', E'ガード待機は危険');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '17', 'アイスクライマー', 'アイクラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '18', 'シーク', 'シーク', '5', '0', E'斜め下は危険');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '19', 'ゼルダ', 'ゼルダ', '2', '7', E'空中待機でガン攻め\r\n地上はガードしない。\r\nコピー');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '20', 'ドクターマリオ', 'ドクマリ', '5', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '21', 'ピチュー', 'ピチュー', '6', '1', E'3%までは前投げ+空前が当たらない');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '22', 'ファルコ', 'ファルコ', '2', '2', E'強攻撃は当たらないので振らない\r\nガン攻め１歩手前待ち\r\n空前/空後');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '23', 'マルス', 'マルス', '4', '7', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '24', 'ルキナ', 'ルキナ', '10', '7', E'真ん中待機\r\n初手：下強＋空前\r\n強攻撃　＋　空前　\r\n下強　＋　空N\r\n復帰阻止は少しだけ\r\nコピーもありかもしれない');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '25', 'こどもリンク', 'ヤンリン', '0', '4', E'初回：引き行動\r\n\r\n地上で相手が来るのを待つ\r\n（１歩上がって2歩下がる）\r\nガード＋掴み回避\r\n');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '26', 'ガノンドルフ', 'ガノン', '47', '37', E'引かない\r\n撃墜：上スマ　　　　　　　　　　　　　　　　　　　　　　　　　　　　');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '27', 'ミュウツー', 'M2', '6', '4', E'しゃがみ姿勢\r\n・上強・下強・吸い込み\r\n・引き空前');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '28', 'ロイ', 'ロイ', '11', '9', E'上強＋下強');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '29', 'クロム', 'クロム', '6', '5', E'コピーして崖上狩り\r\n下強＋上強\r\n２回ジャンプ\r\n擦られている時は弱攻撃？');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '30', 'Mr.ゲーム&ウォッチ', 'ゲッチ', '4', '5', E'3%までは前投げ+空前が当たらない');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '31', 'メタナイト', 'メタ', '2', '1', E'奥読み');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '32', 'ピット・ブラックピット', 'ブラピ', '7', '8', E'ガード＋掴み回避\r\nDAは絶対に振ってはいけない。');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '34', 'ゼロスーツサムス', 'ゼロサム', '2', '4', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '35', 'ワリオ', 'ワリオ', '2', '2', E'対空の判定が強いので\r\n地上で下強＋上強\r\n上スマ');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '36', 'スネーク', 'スネーク', '2', '8', E'ガード掴み\r\n掴み回避');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '37', 'アイク', 'アイクラ', '4', '8', E'ジャンプ禁止\r\n\r\nコピーして崖上狩り\r\n近づかない。\r\n\r\nガーキャン掴み\r\nガード長め');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '38', 'ポケモントレーナー', 'ポケトレ', '3', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '39', 'ディディーコング', 'DD', '4', '2', E'ガード⇒掴み回避\r\n\r\n危険：上スマの発生が速いので不用意に近づかない');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '40', 'リュカ', 'リュカ', '1', '2', E'0%は前投げ+空前が\r\n当たらない');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '41', 'ソニック', 'ソニック', '2', '1', E'空N、DA、上強\r\nガード＋外回避');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '42', 'デデデ', 'DDD', '4', '7', E'ガード長め\r\nその場上り、空前上り\r\n空N、上B');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '43', 'ピクミン＆オリマー', 'ピクオリ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '44', 'ルカリオ', 'ルカリオ', '3', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '45', 'ロボット', 'ロボット', '5', '4', E'ガード長、掴まれたらレバガチャ\r\n\r\n空上＋空上＋空前＋空上');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '46', 'トゥーンリンク', 'トリン', '2', '4', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '47', 'ウルフ', 'ウルフ', '5', '7', E'遠ざかれないように一定の距離を保ちつつ上強\r\n防御：ガード＋掴み回避\r\n攻撃：空上＋横強＋下強\r\n空中暴れしない\r\n');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '48', 'むらびと', 'むらびと', '0', '3', E'空N\r\nガーキャン掴み\r\n\r\n崖近くの復帰は危険（玉が当たる）');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '49', 'ロックマン', '岩', '2', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '50', 'Wii Fit トレーナー', 'フィットレ', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '51', 'ロゼッタ＆チコ', 'ロゼチコ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '52', 'リトルマック', 'リトマ', '16', '14', E'空中で待機');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '53', 'ゲッコウガ', 'ゲコ', '3', '4', E'ガード＋掴み回避\r\n空中暴れしない\r\n遠ざかれないように一定の距離を保ちつつ上強');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '54', '格闘Mii', 'カクミ', '5', '1', E'ステップ防御');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '55', '剣術Mii', 'ケンミ', '3', '3', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '56', '射撃Mii', 'シャゲミ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '57', 'パルテナ', 'パルテナ', '8', '2', E'掴み回避\r\nガード');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '58', 'パックマン', '金玉', '1', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '59', 'ルフレ', 'ルフレ', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '60', 'シュルク', '手越', '8', '3', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '61', 'クッパJr.', 'パジュニ', '3', '5', E'初段：急降下空N、急降下空下、コピー\r\n強攻撃は当たらないので控えめ\r\n\r\n対空リーチが強いので早めに技を振るか逃げるに徹する。\r\n撃墜はなるべく早く横スマや上スマをパナス');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '62', 'ダックハント', '犬', '0', '1', E'捨てげー（着地狩りできない）\r\n犬の目の前で引き空前\r\n\r\n空上＋空前');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '63', 'リュウ', 'リュウ', '0', '0', E'掴めません\r\n反転上強＋DA\r\n下強＋空前\r\n\r\n崖外に出ないで動かずガード安定。\r\n（崖狩りが強いので難しい）');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '64', 'ケン', '剣', '0', '1', E'掴めません\r\n反転上強＋DA\r\n下強＋空前\r\n\r\n崖外に出ないで動かずガード安定。\r\n（崖狩りが強いので難しい）');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '65', 'クラウド', 'クラウド', '13', '7', E'地上付近の空中攻撃\r\n下強\r\n掴み＋空下');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '66', 'カムイ', 'カムイ', '5', '2', E'しゃがみ＋ガード');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '67', 'ベヨネッタ', 'ベヨネッタ', '4', '2', E'防御 + 掴み\r\nY軸ずらし（外ずらし）\r\nジャンプは隙になるので控える\r\n（特に相手が崖につかまってるとき）');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '68', 'インクリング', 'イカ', '2', '3', E'空上＋空N');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '69', 'リドリー', 'リドリー', '6', '10', E'地上戦\r\n下強＋弱か上強で暴れる\r\n（しゃがみ）\r\nガードしない\r\n空中：その場回避、下回避');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '70', 'シモン・リヒター', 'シモリヒ', '1', '0', E'不用意に近づかない\r\nガード');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '72', 'キングクルール', 'キンクル', '15', '19', E'コピー\r\nガード短め\r\nジャンプ');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '73', 'しずえ', 'しずえ', '0', '2', E'崖から必ず戻るようにする（着地狩りが優秀）\r\n上強');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '74', 'ガオガエン', 'ガエン', '2', '6', E'ガードしない\r\n引き空前＋空下');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '75', 'パックンフラワー', '草', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '76', 'ジョーカー', 'J', '11', '9', E'アルセイヌ中スマッシュ禁止\r\n掴み回避多め\r\nガン攻め\r\n');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '77', '勇者', '勇者', '11', '5', E'コピー有\r\n空下＋空前\r\n撃墜：空後');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '78', 'バンジョー＆カズーイ', 'バンカズ', '2', '1', E'ガン攻め（爆弾生成の隙を与えない）');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '79', 'テリー', 'テリー', '7', '9', E'ガード長め、先端の戦い\r\n無理に空前打たない。反転上強＋下強\r\n着地は遠目で\r\n投げは無理（掴めない）\r\n横回避＋弱攻撃');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '80', 'ベレトス', 'ベレトス', '13', '10', E'下強＋上強+空前');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '81', 'ミェンミェン', 'メン', '3', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '82', 'スティーブ', 'スティーブ', '2', '1', E'引きステップ、引きジャンプ\r\n⇒弱攻撃連打（内側横回避）');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '83', 'セフィロス', 'セフィロス', '11', '9', E'奥読み、近づいたら引く\r\n無理して攻撃せずガン攻め下強チクチク攻撃\r\n初手：ガード\r\n終盤：掴み回避、\r\n→撃墜：空N＋透かし空上＋空後\r\n→撃墜：復帰阻止ストーン\r\n→撃墜：横回避＋下スマ\r\n→撃墜：ディレイ空N＋空上\r\n');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '84', 'ホムヒカ', 'ホムヒカ', '10', '9', E'ステップ禁止、空後、直当て上強\r\n空前、ガーキャン掴み、空前＋上強');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '85', 'カズヤ', 'カズヤ', '16', '12', E'ガード、下強\r\n先端当て、掴み回避\r\n崖上は真ん中待機\r\nY軸禁止');
INSERT INTO sumabura.win_loss_manager VALUES ('7', 'カービィ', 'CB', '86', 'ソラ', 'ソラ', '11', '9', E'コピー有');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '1', 'マリオ', 'マリオ', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '2', 'ドンキーコング', 'DK', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '3', 'リンク', 'リンク', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '4', 'サムス・ダークサムス', 'ダムス', '1', '0', E'○：横強、上B');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '6', 'ヨッシー', 'ヨッシー', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '7', 'カービィ', 'CB', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '8', 'フォックス', 'FX', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '9', 'ピカチュウ', 'ピカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '10', 'ルイージ', 'L', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '11', 'ネス', 'ネス', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '12', 'キャプテン・ファルコン', 'CF', '1', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '13', 'プリン', 'プリン', '0', '1', E'○：横B、横強\r\n×：空N');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '14', 'ピーチ・デイジー', 'ピチデ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '16', 'クッパ', 'カメ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '17', 'アイスクライマー', 'アイクラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '18', 'シーク', 'シーク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '19', 'ゼルダ', 'ゼルダ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '20', 'ドクターマリオ', 'ドクマリ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '21', 'ピチュー', 'ピチュー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '22', 'ファルコ', 'ファルコ', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '23', 'マルス', 'マルス', '2', '0', E'×：復帰阻止');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '24', 'ルキナ', 'ルキナ', '1', '2', E'○：横B、空上\r\n×：空N');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '25', 'こどもリンク', 'ヤンリン', '1', '1', E'○：上B\r\n×：膝');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '26', 'ガノンドルフ', 'ガノン', '3', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '27', 'ミュウツー', 'M2', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '28', 'ロイ', 'ロイ', '1', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '29', 'クロム', 'クロム', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '30', 'Mr.ゲーム&ウォッチ', 'ゲッチ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '31', 'メタナイト', 'メタ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '32', 'ピット・ブラックピット', 'ブラピ', '2', '0', E'○：地上差し込み\r\n×：空中差し込み');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '34', 'ゼロスーツサムス', 'ゼロサム', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '35', 'ワリオ', 'ワリオ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '36', 'スネーク', 'スネーク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '37', 'アイク', 'アイクラ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '38', 'ポケモントレーナー', 'ポケトレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '39', 'ディディーコング', 'DD', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '40', 'リュカ', 'リュカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '41', 'ソニック', 'ソニック', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '42', 'デデデ', 'DDD', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '43', 'ピクミン＆オリマー', 'ピクオリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '44', 'ルカリオ', 'ルカリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '45', 'ロボット', 'ロボット', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '46', 'トゥーンリンク', 'トリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '47', 'ウルフ', 'ウルフ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '48', 'むらびと', 'むらびと', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '49', 'ロックマン', '岩', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '50', 'Wii Fit トレーナー', 'フィットレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '51', 'ロゼッタ＆チコ', 'ロゼチコ', '0', '1', E'絶対に勝てない。諦めて待ってろ');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '52', 'リトルマック', 'リトマ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '53', 'ゲッコウガ', 'ゲコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '54', '格闘Mii', 'カクミ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '55', '剣術Mii', 'ケンミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '56', '射撃Mii', 'シャゲミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '57', 'パルテナ', 'パルテナ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '58', 'パックマン', '金玉', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '59', 'ルフレ', 'ルフレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '60', 'シュルク', '手越', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '61', 'クッパJr.', 'パジュニ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '62', 'ダックハント', '犬', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '63', 'リュウ', 'リュウ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '64', 'ケン', '剣', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '65', 'クラウド', 'クラウド', '2', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '66', 'カムイ', 'カムイ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '67', 'ベヨネッタ', 'ベヨネッタ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '68', 'インクリング', 'イカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '69', 'リドリー', 'リドリー', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '70', 'シモン・リヒター', 'シモリヒ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '72', 'キングクルール', 'キンクル', '2', '3', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '73', 'しずえ', 'しずえ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '74', 'ガオガエン', 'ガエン', '0', '0', E'○：飛ばない、置き技、引き行動\r\n×：空下、空中から近づくこと');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '75', 'パックンフラワー', '草', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '76', 'ジョーカー', 'J', '3', '0', E'○：横強、下強、上B（基本は攻めたら負け）\r\n×：前に飛ぶな。');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '77', '勇者', '勇者', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '78', 'バンジョー＆カズーイ', 'バンカズ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '79', 'テリー', 'テリー', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '80', 'ベレトス', 'ベレトス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '81', 'ミェンミェン', 'メン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '82', 'スティーブ', 'スティーブ', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '83', 'セフィロス', 'セフィロス', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '84', 'ホムヒカ', 'ホムヒカ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '85', 'カズヤ', 'カズヤ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('12', 'キャプテン・ファルコン', 'CF', '86', 'ソラ', 'ソラ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '1', 'マリオ', 'マリオ', '4', '0', E'○：空上、降り空N\r\n×：着地暴れ');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '2', 'ドンキーコング', 'DK', '0', '3', E'○：上B、下スマ、空N、横B\r\n△：空後、空前');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '3', 'リンク', 'リンク', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '4', 'サムス・ダークサムス', 'ダムス', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '6', 'ヨッシー', 'ヨッシー', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '7', 'カービィ', 'CB', '2', '2', E'○：スマッシュ全般\r\n×：上B');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '8', 'フォックス', 'FX', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '9', 'ピカチュウ', 'ピカ', '2', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '10', 'ルイージ', 'L', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '11', 'ネス', 'ネス', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '12', 'キャプテン・ファルコン', 'CF', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '13', 'プリン', 'プリン', '5', '3', E'○：スマッシュ、空後、空N、弱\r\n×：横B');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '14', 'ピーチ・デイジー', 'ピチデ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '16', 'クッパ', 'カメ', '1', '3', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '17', 'アイスクライマー', 'アイクラ', '0', '2', E'〇：下強、空前、れっき\r\n×：空N、横B');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '18', 'シーク', 'シーク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '19', 'ゼルダ', 'ゼルダ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '20', 'ドクターマリオ', 'ドクマリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '21', 'ピチュー', 'ピチュー', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '22', 'ファルコ', 'ファルコ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '23', 'マルス', 'マルス', '2', '2', E'×：横強\r\n〇：下強　＋　空N　を交互に');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '24', 'ルキナ', 'ルキナ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '25', 'こどもリンク', 'ヤンリン', '0', '1', E'空Nが当たりません\r\nダメージ：近づいて降り空上？、滑り横強、弱\r\n撃墜：スマッシュ\r\nレッキャクなら少し近づく動作してから打たないと当たってくれない。');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '26', 'ガノンドルフ', 'ガノン', '9', '5', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '27', 'ミュウツー', 'M2', '0', '3', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '28', 'ロイ', 'ロイ', '2', '2', E'近づいてはいけない。\r\n○；弱、れっき、DA、空下\r\n△：横B、空N');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '29', 'クロム', 'クロム', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '30', 'Mr.ゲーム&ウォッチ', 'ゲッチ', '0', '1', E'不利\r\n基本勝てないのでバカになろう。（スマッシュわっふぉい）');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '31', 'メタナイト', 'メタ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '32', 'ピット・ブラックピット', 'ブラピ', '2', '3', E'○：ガード掴み、れっき、空上\r\n△：空N、下強');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '34', 'ゼロスーツサムス', 'ゼロサム', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '35', 'ワリオ', 'ワリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '36', 'スネーク', 'スネーク', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '37', 'アイク', 'アイクラ', '0', '4', E'〇：空前、空N\r\n×：空下');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '38', 'ポケモントレーナー', 'ポケトレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '39', 'ディディーコング', 'DD', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '40', 'リュカ', 'リュカ', '1', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '41', 'ソニック', 'ソニック', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '42', 'デデデ', 'DDD', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '43', 'ピクミン＆オリマー', 'ピクオリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '44', 'ルカリオ', 'ルカリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '45', 'ロボット', 'ロボット', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '46', 'トゥーンリンク', 'トリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '47', 'ウルフ', 'ウルフ', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '48', 'むらびと', 'むらびと', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '49', 'ロックマン', '岩', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '50', 'Wii Fit トレーナー', 'フィットレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '51', 'ロゼッタ＆チコ', 'ロゼチコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '52', 'リトルマック', 'リトマ', '1', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '53', 'ゲッコウガ', 'ゲコ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '54', '格闘Mii', 'カクミ', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '55', '剣術Mii', 'ケンミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '56', '射撃Mii', 'シャゲミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '57', 'パルテナ', 'パルテナ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '58', 'パックマン', '金玉', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '59', 'ルフレ', 'ルフレ', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '60', 'シュルク', '手越', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '61', 'クッパJr.', 'パジュニ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '62', 'ダックハント', '犬', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '63', 'リュウ', 'リュウ', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '64', 'ケン', '剣', '3', '0', E'○：空N');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '65', 'クラウド', 'クラウド', '1', '2', E'崖上ガーキャン弱・横強、降り空N\r\n上スマ');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '66', 'カムイ', 'カムイ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '67', 'ベヨネッタ', 'ベヨネッタ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '68', 'インクリング', 'イカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '69', 'リドリー', 'リドリー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '70', 'シモン・リヒター', 'シモリヒ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '72', 'キングクルール', 'キンクル', '3', '5', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '73', 'しずえ', 'しずえ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '74', 'ガオガエン', 'ガエン', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '75', 'パックンフラワー', '草', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '76', 'ジョーカー', 'J', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '77', '勇者', '勇者', '0', '0', E'○：掴み回避、下強\r\n×：ジャンプ');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '78', 'バンジョー＆カズーイ', 'バンカズ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '79', 'テリー', 'テリー', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '80', 'ベレトス', 'ベレトス', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '81', 'ミェンミェン', 'メン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '82', 'スティーブ', 'スティーブ', '2', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '83', 'セフィロス', 'セフィロス', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '84', 'ホムヒカ', 'ホムヒカ', '2', '0', E'基本勝てないので真面目に戦わないこと');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '85', 'カズヤ', 'カズヤ', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('26', 'ガノンドルフ', 'ガノン', '86', 'ソラ', 'ソラ', '0', '2', E'超不利\r\n上スマぶんぶん\r\n空下ぶんぶん');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '1', 'マリオ', 'マリオ', '3', '2', E'崖上空後、横スマ、横B、ブリザガ');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '2', 'ドンキーコング', 'DK', '2', '2', E'降り空上、空N');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '3', 'リンク', 'リンク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '4', 'サムス・ダークサムス', 'ダムス', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '6', 'ヨッシー', 'ヨッシー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '7', 'カービィ', 'CB', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '8', 'フォックス', 'FX', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '9', 'ピカチュウ', 'ピカ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '10', 'ルイージ', 'L', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '11', 'ネス', 'ネス', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '12', 'キャプテン・ファルコン', 'CF', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '13', 'プリン', 'プリン', '2', '0', E'注意して空N、空後で刺し返すのは有り');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '14', 'ピーチ・デイジー', 'ピチデ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '16', 'クッパ', 'カメ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '17', 'アイスクライマー', 'アイクラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '18', 'シーク', 'シーク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '19', 'ゼルダ', 'ゼルダ', '1', '0', E'崖上ガード、空後、横スマ');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '20', 'ドクターマリオ', 'ドクマリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '21', 'ピチュー', 'ピチュー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '22', 'ファルコ', 'ファルコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '23', 'マルス', 'マルス', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '24', 'ルキナ', 'ルキナ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '25', 'こどもリンク', 'ヤンリン', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '26', 'ガノンドルフ', 'ガノン', '2', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '27', 'ミュウツー', 'M2', '0', '1', E'相手は基本、DAとシャドボでガン待ち\r\n飛び道具負けしているので\r\nスマッシュ多めで\r\nコンボ中に魔法\r\n\r\n掴みが通る。');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '28', 'ロイ', 'ロイ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '29', 'クロム', 'クロム', '1', '0', E'○：空N、ガーキャン上B\r\n△：下強、横B、横強');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '30', 'Mr.ゲーム&ウォッチ', 'ゲッチ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '31', 'メタナイト', 'メタ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '32', 'ピット・ブラックピット', 'ブラピ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '34', 'ゼロスーツサムス', 'ゼロサム', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '35', 'ワリオ', 'ワリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '36', 'スネーク', 'スネーク', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '37', 'アイク', 'アイクラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '38', 'ポケモントレーナー', 'ポケトレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '39', 'ディディーコング', 'DD', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '40', 'リュカ', 'リュカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '41', 'ソニック', 'ソニック', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '42', 'デデデ', 'DDD', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '43', 'ピクミン＆オリマー', 'ピクオリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '44', 'ルカリオ', 'ルカリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '45', 'ロボット', 'ロボット', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '46', 'トゥーンリンク', 'トリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '47', 'ウルフ', 'ウルフ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '48', 'むらびと', 'むらびと', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '49', 'ロックマン', '岩', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '50', 'Wii Fit トレーナー', 'フィットレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '51', 'ロゼッタ＆チコ', 'ロゼチコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '52', 'リトルマック', 'リトマ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '53', 'ゲッコウガ', 'ゲコ', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '54', '格闘Mii', 'カクミ', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '55', '剣術Mii', 'ケンミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '56', '射撃Mii', 'シャゲミ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '57', 'パルテナ', 'パルテナ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '58', 'パックマン', '金玉', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '59', 'ルフレ', 'ルフレ', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '60', 'シュルク', '手越', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '61', 'クッパJr.', 'パジュニ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '62', 'ダックハント', '犬', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '63', 'リュウ', 'リュウ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '64', 'ケン', '剣', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '65', 'クラウド', 'クラウド', '0', '1', E'微不利\r\n○：横強、下強\r\n△：ジャンプ、空N（必ず引きジャンプすること）');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '66', 'カムイ', 'カムイ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '67', 'ベヨネッタ', 'ベヨネッタ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '68', 'インクリング', 'イカ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '69', 'リドリー', 'リドリー', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '70', 'シモン・リヒター', 'シモリヒ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '72', 'キングクルール', 'キンクル', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '73', 'しずえ', 'しずえ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '74', 'ガオガエン', 'ガエン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '75', 'パックンフラワー', '草', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '76', 'ジョーカー', 'J', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '77', '勇者', '勇者', '2', '3', E'空中ジャンプ注意\r\n○：弱(弱一段止め）\r\n△：空N');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '78', 'バンジョー＆カズーイ', 'バンカズ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '79', 'テリー', 'テリー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '80', 'ベレトス', 'ベレトス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '81', 'ミェンミェン', 'メン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '82', 'スティーブ', 'スティーブ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '83', 'セフィロス', 'セフィロス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '84', 'ホムヒカ', 'ホムヒカ', '1', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '85', 'カズヤ', 'カズヤ', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('86', 'ソラ', 'ソラ', '86', 'ソラ', 'ソラ', '2', '0', E'魔法、NBを擦る');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '1', 'マリオ', 'マリオ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '2', 'ドンキーコング', 'DK', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '3', 'リンク', 'リンク', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '4', 'サムス・ダークサムス', 'ダムス', '1', '1', E'○：NB、上スマ、下スマ\r\n×：横強');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '6', 'ヨッシー', 'ヨッシー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '7', 'カービィ', 'CB', '3', '0', E'横B、上スマ、横スマ');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '8', 'フォックス', 'FX', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '9', 'ピカチュウ', 'ピカ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '10', 'ルイージ', 'L', '1', '0', E'○：NB、横B');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '11', 'ネス', 'ネス', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '12', 'キャプテン・ファルコン', 'CF', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '13', 'プリン', 'プリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '14', 'ピーチ・デイジー', 'ピチデ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '16', 'クッパ', 'カメ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '17', 'アイスクライマー', 'アイクラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '18', 'シーク', 'シーク', '0', '1', E'少し不利\r\n○：掴み、空N、空前、空後\r\n×：横強、空上、下強、カウンター');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '19', 'ゼルダ', 'ゼルダ', '1', '0', E'○：NB+掴み、横B\r\n横スマ\r\n△：カウンター');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '20', 'ドクターマリオ', 'ドクマリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '21', 'ピチュー', 'ピチュー', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '22', 'ファルコ', 'ファルコ', '1', '0', E'相手が着地している時は、ガードするといい');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '23', 'マルス', 'マルス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '24', 'ルキナ', 'ルキナ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '25', 'こどもリンク', 'ヤンリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '26', 'ガノンドルフ', 'ガノン', '2', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '27', 'ミュウツー', 'M2', '2', '0', E'有利：崖待機に近づかず横Bでけん制\r\n○：NB、横B、空上、掴み');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '28', 'ロイ', 'ロイ', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '29', 'クロム', 'クロム', '1', '0', E'○：カウンター、空上、空N、弱\r\n×：横B');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '30', 'Mr.ゲーム&ウォッチ', 'ゲッチ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '31', 'メタナイト', 'メタ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '32', 'ピット・ブラックピット', 'ブラピ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '34', 'ゼロスーツサムス', 'ゼロサム', '0', '2', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '35', 'ワリオ', 'ワリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '36', 'スネーク', 'スネーク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '37', 'アイク', 'アイクラ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '38', 'ポケモントレーナー', 'ポケトレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '39', 'ディディーコング', 'DD', '0', '1', E'微不利：気を付けて戦おう。無理そうなら下スマ連打で\r\n○：弱\r\n△：空N');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '40', 'リュカ', 'リュカ', '1', '0', E'○：横Bで回復させるモーションを入れさせる。、掴み、空下\r\n降り空前\r\n△：空N\r\n\r\n撃墜：上スマ、下スマ');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '41', 'ソニック', 'ソニック', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '42', 'デデデ', 'DDD', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '43', 'ピクミン＆オリマー', 'ピクオリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '44', 'ルカリオ', 'ルカリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '45', 'ロボット', 'ロボット', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '46', 'トゥーンリンク', 'トリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '47', 'ウルフ', 'ウルフ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '48', 'むらびと', 'むらびと', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '49', 'ロックマン', '岩', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '50', 'Wii Fit トレーナー', 'フィットレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '51', 'ロゼッタ＆チコ', 'ロゼチコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '52', 'リトルマック', 'リトマ', '2', '1', E'○：崖降り空N、弱、掴み、スマッシュ、空上、空下\r\n△：空N、横強、空前、横B');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '53', 'ゲッコウガ', 'ゲコ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '54', '格闘Mii', 'カクミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '55', '剣術Mii', 'ケンミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '56', '射撃Mii', 'シャゲミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '57', 'パルテナ', 'パルテナ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '58', 'パックマン', '金玉', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '59', 'ルフレ', 'ルフレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '60', 'シュルク', '手越', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '61', 'クッパJr.', 'パジュニ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '62', 'ダックハント', '犬', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '63', 'リュウ', 'リュウ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '64', 'ケン', '剣', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '65', 'クラウド', 'クラウド', '0', '0', E'○：降り空上、空N、NB\r\n△：横B');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '66', 'カムイ', 'カムイ', '1', '1', E'○：横B、掴み、弱、降り空N\r\n△：空N（上り）、空前、空上、DA');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '67', 'ベヨネッタ', 'ベヨネッタ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '68', 'インクリング', 'イカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '69', 'リドリー', 'リドリー', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '70', 'シモン・リヒター', 'シモリヒ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '72', 'キングクルール', 'キンクル', '0', '2', E'○：空上、空N\r\n△：上スマ、横強');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '73', 'しずえ', 'しずえ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '74', 'ガオガエン', 'ガエン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '75', 'パックンフラワー', '草', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '76', 'ジョーカー', 'J', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '77', '勇者', '勇者', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '78', 'バンジョー＆カズーイ', 'バンカズ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '79', 'テリー', 'テリー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '80', 'ベレトス', 'ベレトス', '2', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '81', 'ミェンミェン', 'メン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '82', 'スティーブ', 'スティーブ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '83', 'セフィロス', 'セフィロス', '0', '2', E'○：NB');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '84', 'ホムヒカ', 'ホムヒカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '85', 'カズヤ', 'カズヤ', '1', '1', E'○：横B、横スマ\r\n△：空N');
INSERT INTO sumabura.win_loss_manager VALUES ('57', 'パルテナ', 'パルテナ', '86', 'ソラ', 'ソラ', '1', '0', E'空Nに対してはしっかりまでちゃんとガードする。\r\n○：投げ＋空上');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '1', 'マリオ', 'マリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '2', 'ドンキーコング', 'DK', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '3', 'リンク', 'リンク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '4', 'サムス・ダークサムス', 'ダムス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '6', 'ヨッシー', 'ヨッシー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '7', 'カービィ', 'CB', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '8', 'フォックス', 'FX', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '9', 'ピカチュウ', 'ピカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '10', 'ルイージ', 'L', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '11', 'ネス', 'ネス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '12', 'キャプテン・ファルコン', 'CF', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '13', 'プリン', 'プリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '14', 'ピーチ・デイジー', 'ピチデ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '16', 'クッパ', 'カメ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '17', 'アイスクライマー', 'アイクラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '18', 'シーク', 'シーク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '19', 'ゼルダ', 'ゼルダ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '20', 'ドクターマリオ', 'ドクマリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '21', 'ピチュー', 'ピチュー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '22', 'ファルコ', 'ファルコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '23', 'マルス', 'マルス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '24', 'ルキナ', 'ルキナ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '25', 'こどもリンク', 'ヤンリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '26', 'ガノンドルフ', 'ガノン', '3', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '27', 'ミュウツー', 'M2', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '28', 'ロイ', 'ロイ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '29', 'クロム', 'クロム', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '30', 'Mr.ゲーム&ウォッチ', 'ゲッチ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '31', 'メタナイト', 'メタ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '32', 'ピット・ブラックピット', 'ブラピ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '34', 'ゼロスーツサムス', 'ゼロサム', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '35', 'ワリオ', 'ワリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '36', 'スネーク', 'スネーク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '37', 'アイク', 'アイクラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '38', 'ポケモントレーナー', 'ポケトレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '39', 'ディディーコング', 'DD', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '40', 'リュカ', 'リュカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '41', 'ソニック', 'ソニック', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '42', 'デデデ', 'DDD', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '43', 'ピクミン＆オリマー', 'ピクオリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '44', 'ルカリオ', 'ルカリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '45', 'ロボット', 'ロボット', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '46', 'トゥーンリンク', 'トリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '47', 'ウルフ', 'ウルフ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '48', 'むらびと', 'むらびと', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '49', 'ロックマン', '岩', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '50', 'Wii Fit トレーナー', 'フィットレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '51', 'ロゼッタ＆チコ', 'ロゼチコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '52', 'リトルマック', 'リトマ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '53', 'ゲッコウガ', 'ゲコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '54', '格闘Mii', 'カクミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '55', '剣術Mii', 'ケンミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '56', '射撃Mii', 'シャゲミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '57', 'パルテナ', 'パルテナ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '58', 'パックマン', '金玉', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '59', 'ルフレ', 'ルフレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '60', 'シュルク', '手越', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '61', 'クッパJr.', 'パジュニ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '62', 'ダックハント', '犬', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '63', 'リュウ', 'リュウ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '64', 'ケン', '剣', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '65', 'クラウド', 'クラウド', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '66', 'カムイ', 'カムイ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '67', 'ベヨネッタ', 'ベヨネッタ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '68', 'インクリング', 'イカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '69', 'リドリー', 'リドリー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '70', 'シモン・リヒター', 'シモリヒ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '72', 'キングクルール', 'キンクル', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '73', 'しずえ', 'しずえ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '74', 'ガオガエン', 'ガエン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '75', 'パックンフラワー', '草', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '76', 'ジョーカー', 'J', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '77', '勇者', '勇者', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '78', 'バンジョー＆カズーイ', 'バンカズ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '79', 'テリー', 'テリー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '80', 'ベレトス', 'ベレトス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '81', 'ミェンミェン', 'メン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '82', 'スティーブ', 'スティーブ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '83', 'セフィロス', 'セフィロス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '84', 'ホムヒカ', 'ホムヒカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '85', 'カズヤ', 'カズヤ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('27', 'ミュウツー', 'M2', '86', 'ソラ', 'ソラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '1', 'マリオ', 'マリオ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '2', 'ドンキーコング', 'DK', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '3', 'リンク', 'リンク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '4', 'サムス・ダークサムス', 'ダムス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '6', 'ヨッシー', 'ヨッシー', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '7', 'カービィ', 'CB', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '8', 'フォックス', 'FX', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '9', 'ピカチュウ', 'ピカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '10', 'ルイージ', 'L', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '11', 'ネス', 'ネス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '12', 'キャプテン・ファルコン', 'CF', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '13', 'プリン', 'プリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '14', 'ピーチ・デイジー', 'ピチデ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '16', 'クッパ', 'カメ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '17', 'アイスクライマー', 'アイクラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '18', 'シーク', 'シーク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '19', 'ゼルダ', 'ゼルダ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '20', 'ドクターマリオ', 'ドクマリ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '21', 'ピチュー', 'ピチュー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '22', 'ファルコ', 'ファルコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '23', 'マルス', 'マルス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '24', 'ルキナ', 'ルキナ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '25', 'こどもリンク', 'ヤンリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '26', 'ガノンドルフ', 'ガノン', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '27', 'ミュウツー', 'M2', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '28', 'ロイ', 'ロイ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '29', 'クロム', 'クロム', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '30', 'Mr.ゲーム&ウォッチ', 'ゲッチ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '31', 'メタナイト', 'メタ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '32', 'ピット・ブラックピット', 'ブラピ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '34', 'ゼロスーツサムス', 'ゼロサム', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '35', 'ワリオ', 'ワリオ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '36', 'スネーク', 'スネーク', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '37', 'アイク', 'アイクラ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '38', 'ポケモントレーナー', 'ポケトレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '39', 'ディディーコング', 'DD', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '40', 'リュカ', 'リュカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '41', 'ソニック', 'ソニック', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '42', 'デデデ', 'DDD', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '43', 'ピクミン＆オリマー', 'ピクオリ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '44', 'ルカリオ', 'ルカリオ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '45', 'ロボット', 'ロボット', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '46', 'トゥーンリンク', 'トリン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '47', 'ウルフ', 'ウルフ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '48', 'むらびと', 'むらびと', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '49', 'ロックマン', '岩', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '50', 'Wii Fit トレーナー', 'フィットレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '51', 'ロゼッタ＆チコ', 'ロゼチコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '52', 'リトルマック', 'リトマ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '53', 'ゲッコウガ', 'ゲコ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '54', '格闘Mii', 'カクミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '55', '剣術Mii', 'ケンミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '56', '射撃Mii', 'シャゲミ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '57', 'パルテナ', 'パルテナ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '58', 'パックマン', '金玉', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '59', 'ルフレ', 'ルフレ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '60', 'シュルク', '手越', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '61', 'クッパJr.', 'パジュニ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '62', 'ダックハント', '犬', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '63', 'リュウ', 'リュウ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '64', 'ケン', '剣', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '65', 'クラウド', 'クラウド', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '66', 'カムイ', 'カムイ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '67', 'ベヨネッタ', 'ベヨネッタ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '68', 'インクリング', 'イカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '69', 'リドリー', 'リドリー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '70', 'シモン・リヒター', 'シモリヒ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '72', 'キングクルール', 'キンクル', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '73', 'しずえ', 'しずえ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '74', 'ガオガエン', 'ガエン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '75', 'パックンフラワー', '草', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '76', 'ジョーカー', 'J', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '77', '勇者', '勇者', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '78', 'バンジョー＆カズーイ', 'バンカズ', '1', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '79', 'テリー', 'テリー', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '80', 'ベレトス', 'ベレトス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '81', 'ミェンミェン', 'メン', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '82', 'スティーブ', 'スティーブ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '83', 'セフィロス', 'セフィロス', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '84', 'ホムヒカ', 'ホムヒカ', '0', '0', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '85', 'カズヤ', 'カズヤ', '0', '1', E'');
INSERT INTO sumabura.win_loss_manager VALUES ('16', 'クッパ', 'カメ', '86', 'ソラ', 'ソラ', '0', '0', E'');

